[workspace]
name = "earthcode_cubes"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]
exclude-newer = "20 days"


[dependencies]
python = "3.13.*"
ipykernel = ">=6,<8"
jupyterlab = ">=4.6.1,<5"
jupytext = ">=1,<2"
numpy = ">=1.26,<3"
pandas = ">=2,<4"
xarray = ">=2025,<2027"
xesmf = ">=0.9,<1"
esmpy = ">=8,<9"
dask = ">=2025,<2027"
distributed = ">=2025,<2027"
geopandas = ">=1,<2"
rasterio = ">=1.4,<2"
rioxarray = ">=0.19,<1"
pyproj = ">=3,<4"
shapely = ">=2,<3"
matplotlib-base = ">=3,<4"
scipy = ">=1,<2"
sparse = ">=0.16,<1"
pyarrow = ">=18,<24"
netcdf4 = ">=1,<2"
zarr = ">=3,<4"
fsspec = ">=2025,<2027"
s3fs = ">=2025,<2027"
pystac = ">=1,<2"
odc-stac = ">=0.4,<1"
ipywidgets = ">=8,<9"
pytest = ">=8,<10"
pyresample = ">=1.35.0,<2"
hvplot = ">=0.12.2,<0.13"
geoviews = ">=1.15.1,<2"
graphviz = ">=14.1.2,<15"
h5netcdf = ">=1.8.1,<2"
obspec_utils = ">=0.9.0,<0.10"
obstore = ">=0.11.0,<0.12"
virtualizarr = ">=2.7.1,<3"
icechunk = ">=2.1.1,<3"

[pypi-dependencies]
geozarr-toolkit = ">=0.1.2,<0.2"
ipyeoxelements = ">=1.1,<2"
xstac = ">=1.2,<2"
